import { useState, useEffect } from "react";
import { Bug, Search, RefreshCw, Terminal, AlertTriangle, ShieldAlert, FileCode, Trash2 } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "../components/ui/card";
import { Button } from "../components/ui/button";
import { ScrollArea } from "../components/ui/scroll-area";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "../components/ui/table";
import api from "../lib/api";
import { toast } from "sonner";

export default function CoreCrashAnalyzer() {
  const [cores, setCores] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);
  const [analyzing, setAnalyzing] = useState(false);
  const [gdbOutput, setGdbOutput] = useState<string>("");
  const [activeCore, setActiveCore] = useState<string | null>(null);

  const fetchCores = async () => {
    setLoading(true);
    try {
      // Simulated SSH command to find game.core files
      await api.post("/api/console/command", { command: "find /usr/game/cores -name 'game.core'" });
      
      // Mocking core files found
      setCores([
        { path: "channel1/core1", size: "145 MB", date: "2024-04-14 14:20:00", has_core: true },
        { path: "channel1/core2", size: "-", date: "-", has_core: false },
        { path: "channel2/core1", size: "-", date: "-", has_core: false },
        { path: "game99", size: "210 MB", date: "2024-04-13 09:15:00", has_core: true },
        { path: "db", size: "-", date: "-", has_core: false },
        { path: "auth", size: "-", date: "-", has_core: false },
      ]);
    } catch (err: any) {
      toast.error("Core listesi alınamadı.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchCores();
  }, []);

  const analyzeCore = async (corePath: string) => {
    setAnalyzing(true);
    setActiveCore(corePath);
    setGdbOutput(`[root@metin2-srv ~]# gdb -batch -ex "bt full" /usr/game/share/bin/game /usr/game/cores/${corePath}/game.core\n\nReading symbols from /usr/game/share/bin/game...\n[New LWP 12345]\nCore was generated by './game'.\nProgram terminated with signal SIGSEGV, Segmentation fault.\n#0  0x08123456 in CHARACTER::Damage (this=0x0, pAttacker=0xf5a12340, damage=500, type=0) at char_battle.cpp:1250\n...`);
    
    try {
      // Simulated GDB command via SSH
      await api.post("/api/console/command", { 
        command: `gdb -batch -ex "bt full" /usr/game/share/bin/game /usr/game/cores/${corePath}/game.core` 
      });
      
      setTimeout(() => {
        setGdbOutput(prev => prev + `\n\n#1  0x08124567 in battle_melee_attack (ch=0xf5a12340, victim=0x0) at battle.cpp:450\n#2  0x08125678 in CHARACTER::Attack (this=0xf5a12340, victim=0x0) at char_state.cpp:890\n#3  0x08126789 in main (argc=1, argv=0xffffd120) at main.cpp:320\n\n(gdb) quit\nAnalysis complete.`);
        setAnalyzing(false);
        toast.success(`${corePath} analizi tamamlandı.`);
      }, 1500);
    } catch (err: any) {
      toast.error("GDB analizi başarısız.");
      setAnalyzing(false);
    }
  };

  const deleteCore = async (corePath: string) => {
    try {
      await api.post("/api/console/command", { command: `rm -f /usr/game/cores/${corePath}/game.core` });
      toast.success(`${corePath} core dosyası silindi.`);
      fetchCores();
      if (activeCore === corePath) {
        setGdbOutput("");
        setActiveCore(null);
      }
    } catch (err: any) {
      toast.error("Silme işlemi başarısız.");
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-3xl font-bold tracking-tight">Core Düşme Analizi (GDB)</h2>
          <p className="text-muted-foreground">Sunucu çökmelerini (game.core) SSH üzerinden GDB ile analiz edin.</p>
        </div>
        <Button variant="outline" onClick={fetchCores} disabled={loading} className="gap-2">
          <RefreshCw size={18} className={loading ? "animate-spin" : ""} /> Yenile
        </Button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <Card className="lg:col-span-1">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <AlertTriangle className="text-amber-500" size={20} /> Çöken Çekirdekler
            </CardTitle>
            <CardDescription>/usr/game/cores/*/game.core</CardDescription>
          </CardHeader>
          <CardContent className="p-0">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Çekirdek</TableHead>
                  <TableHead className="text-right">İşlem</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {cores.map((core, i) => (
                  <TableRow key={i} className={core.has_core ? "bg-red-500/5" : ""}>
                    <TableCell>
                      <div className="flex flex-col">
                        <span className={`font-bold ${core.has_core ? "text-red-500" : "text-muted-foreground"}`}>
                          {core.path}
                        </span>
                        {core.has_core && (
                          <span className="text-[10px] text-muted-foreground font-mono">
                            {core.size} | {core.date}
                          </span>
                        )}
                      </div>
                    </TableCell>
                    <TableCell className="text-right">
                      {core.has_core ? (
                        <div className="flex justify-end gap-1">
                          <Button 
                            variant="ghost" 
                            size="icon" 
                            className="text-blue-500 hover:text-blue-600 hover:bg-blue-500/10"
                            onClick={() => analyzeCore(core.path)}
                            disabled={analyzing}
                          >
                            <Bug size={16} />
                          </Button>
                          <Button 
                            variant="ghost" 
                            size="icon" 
                            className="text-red-500 hover:text-red-600 hover:bg-red-500/10"
                            onClick={() => deleteCore(core.path)}
                          >
                            <Trash2 size={16} />
                          </Button>
                        </div>
                      ) : (
                        <span className="text-xs text-emerald-500 font-bold">Temiz</span>
                      )}
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </CardContent>
        </Card>

        <Card className="lg:col-span-2">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Terminal className="text-blue-500" size={20} /> GDB Backtrace Çıktısı
            </CardTitle>
            <CardDescription>
              {activeCore ? `${activeCore} için hata ayıklama sonuçları.` : "Analiz etmek için sol taraftan bir core seçin."}
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="bg-[#0c0c0c] text-[#00ff00] p-4 rounded-lg font-mono text-xs h-[500px] overflow-y-auto whitespace-pre-wrap border border-border/50 shadow-inner">
              {analyzing && !gdbOutput.includes("Analysis complete") ? (
                <div className="flex items-center gap-2 text-amber-500">
                  <RefreshCw size={14} className="animate-spin" /> GDB sembolleri okuyor ve backtrace oluşturuyor...
                </div>
              ) : null}
              {gdbOutput || <span className="text-muted-foreground italic">GDB çıktısı bekleniyor...</span>}
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
